#!/usr/bin/env bash
# PRAXIS v2.0 — One-shot production setup.
# Run as root on a fresh Ubuntu 22.04 / 24.04 server.
# Idempotent: safe to re-run.
set -euo pipefail

PRAXIS_HOME=/opt/praxis
PRAXIS_USER=praxis
GITHUB_REPO="https://github.com/cptunderpantsmoons/praxis-v2.git"

log() { printf "\033[1;34m[setup]\033[0m %s\n" "$*"; }
fail() { printf "\033[1;31m[FAIL]\033[0m %s\n" "$*"; exit 1; }

[ "$EUID" -ne 0 ] && fail "Run as root: bash deploy/setup.sh"
log "Detected OS: $(. /etc/os-release; echo "$ID $VERSION_ID")"

# ── 1. Install Docker if missing ────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release; echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi
log "Docker: $(docker --version)"

# ── 2. Install uv (for running tests / dev tools) ─────────
if ! command -v uv >/dev/null 2>&1; then
  log "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

# ── 3. Create praxis user ──────────────────────────────────
if ! id "$PRAXIS_USER" >/dev/null 2>&1; then
  useradd -r -m -s /bin/bash -G docker "$PRAXIS_USER"
fi
mkdir -p "$PRAXIS_HOME"
chown -R "$PRAXIS_USER:$PRAXIS_USER" "$PRAXIS_HOME"

# ── 4. Clone the repo ──────────────────────────────────────
if [ ! -d "$PRAXIS_HOME/repo/.git" ]; then
  log "Cloning $GITHUB_REPO into $PRAXIS_HOME/repo"
  sudo -u "$PRAXIS_USER" git clone "$GITHUB_REPO" "$PRAXIS_HOME/repo"
else
  log "Repo already cloned, pulling latest"
  sudo -u "$PRAXIS_USER" -H bash -c "cd $PRAXIS_HOME/repo && git pull --rebase"
fi

# ── 5. Create .env if missing ──────────────────────────────
ENV_FILE="$PRAXIS_HOME/repo/.env"
if [ ! -f "$ENV_FILE" ]; then
  log "Creating .env (interactive — paste your keys now)"
  cat > "$ENV_FILE" <<'ENV_TEMPLATE'
# PRAXIS v2.0 — Production secrets (chmod 600)
# Generated by deploy/setup.sh — edit values, then restart.

ENVIRONMENT=production
HOST=0.0.0.0
PORT=8000

# ── AgentMail (inbound + outbound email) ──────────────────
AGENTMAIL_API_KEY=*** AGENTMAIL_INBOX_ID=ib_praxis2
AGENTMAIL_WEBHOOK_SECRET=*** ── Umans Inference (LLM) ───────────────────────
UMANS_API_KEY=*** _BASE_URL=https://api.code.umans.ai/v1
UMANS_GLM_CONTEXT_WINDOW=1000000
UMANS_KIMI_CONTEXT_WINDOW=131072
UMANS_QWEN_CONTEXT_WINDOW=131072

# ── Neo4j (graph DB) ──────────────────────────────────────
NEO4J_URI=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=*** ── Qdrant (vector DB) ───────────────────────────────────
QDRANT_URL=http://qdrant:6333
QDRANT_API_KEY=*** ── PostgreSQL (LangGraph checkpointing) ─────────────
POSTGRES_DSN=postgresql://praxis:***@postgres:5432/praxis

# ── Webhook public URL ────────────────────────────────────
PUBLIC_URL=http://2.25.195.193:8000
ENV_TEMPLATE
  chown "$PRAXIS_USER:$PRAXIS_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log ">>> EDIT $ENV_FILE NOW and replace the *** placeholders with your real keys"
  log ">>> Then re-run this script to continue"
  exit 0
fi
chmod 600 "$ENV_FILE"
log ".env found, perms OK"

# ── 6. Start infra (postgres, neo4j, qdrant) ──────────────
cd "$PRAXIS_HOME/repo"
log "Starting Neo4j + Qdrant + PostgreSQL..."
sudo -u "$PRAXIS_USER" docker compose up -d neo4j qdrant postgres
log "Waiting for services to be healthy (60s timeout)..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:6333/healthz >/dev/null && \
     curl -sf http://localhost:7474/ >/dev/null && \
     PGPASSWORD=*** -d praxis -c "SELECT 1" >/dev/null 2>&1; then
    log "All infra services healthy"
    break
  fi
  sleep 2
done

# ── 7. Build and start PRAXIS app ─────────────────────────
log "Building PRAXIS Docker image..."
sudo -u "$PRAXIS_USER" docker build -t praxis:0.1.0 .
log "Starting PRAXIS app..."
sudo -u "$PRAXIS_USER" docker compose up -d app

# ── 8. Wait for /health, then run smoke test ──────────────
log "Waiting for /health..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:8000/health >/dev/null; then
    log "PRAXIS is up!"
    curl -s http://localhost:8000/health
    echo
    break
  fi
  sleep 2
done

log "Running smoke test..."
SMOKE_ALLOW_GRAPH_FAILURE=0 bash ci-cd/smoke-test.sh http://localhost:8000

log ""
log "=========================================="
log "  PRAXIS v2.0 deployed successfully"
log "  URL: http://2.25.195.193:8000"
log "  Health: http://2.25.195.193:8000/health"
log "  Logs: docker compose logs -f app"
log "=========================================="
